# Generated by Django 3.2 on 2021-05-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_content_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='introduction',
            field=models.TextField(max_length=500),
        ),
    ]
